services:
  backend:
    build: .
    container_name: amigopet-backend
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: amigopet-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: amigopet
    ports:
      - "5433:5432"
